python train_NF_prior.py --submit --population-type gaussian --source-type bns --eos-samples-name radio
python train_NF_prior.py --submit --population-type gaussian --source-type bns --eos-samples-name radio_chiEFT
python train_NF_prior.py --submit --population-type gaussian --source-type bns --eos-samples-name radio_chiEFT_NICER
python train_NF_prior.py --submit --population-type gaussian --source-type nsbh --eos-samples-name radio
python train_NF_prior.py --submit --population-type gaussian --source-type nsbh --eos-samples-name radio_chiEFT
python train_NF_prior.py --submit --population-type gaussian --source-type nsbh --eos-samples-name radio_chiEFT_NICER
python train_NF_prior.py --submit --population-type double_gaussian --source-type bns --eos-samples-name radio
python train_NF_prior.py --submit --population-type double_gaussian --source-type bns --eos-samples-name radio_chiEFT
python train_NF_prior.py --submit --population-type double_gaussian --source-type bns --eos-samples-name radio_chiEFT_NICER
python train_NF_prior.py --submit --population-type double_gaussian --source-type nsbh --eos-samples-name radio
python train_NF_prior.py --submit --population-type double_gaussian --source-type nsbh --eos-samples-name radio_chiEFT
python train_NF_prior.py --submit --population-type double_gaussian --source-type nsbh --eos-samples-name radio_chiEFT_NICER