#!/bin/bash

python train_NF_prior.py --submit --population-type uniform --source-type bns --eos-samples-name radio --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type uniform --source-type bns --eos-samples-name radio_chiEFT --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type uniform --source-type bns --eos-samples-name radio_chiEFT_NICER --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type gaussian --source-type bns --eos-samples-name radio --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type gaussian --source-type bns --eos-samples-name radio_chiEFT --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type gaussian --source-type bns --eos-samples-name radio_chiEFT_NICER --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type double_gaussian --source-type bns --eos-samples-name radio --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type double_gaussian --source-type bns --eos-samples-name radio_chiEFT --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type double_gaussian --source-type bns --eos-samples-name radio_chiEFT_NICER --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type uniform --source-type nsbh --eos-samples-name radio --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type uniform --source-type nsbh --eos-samples-name radio_chiEFT --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type uniform --source-type nsbh --eos-samples-name radio_chiEFT_NICER --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type gaussian --source-type nsbh --eos-samples-name radio --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type gaussian --source-type nsbh --eos-samples-name radio_chiEFT --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type gaussian --source-type nsbh --eos-samples-name radio_chiEFT_NICER --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type double_gaussian --source-type nsbh --eos-samples-name radio --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type double_gaussian --source-type nsbh --eos-samples-name radio_chiEFT --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16
python train_NF_prior.py --submit --population-type double_gaussian --source-type nsbh --eos-samples-name radio_chiEFT_NICER --batch-size 1024 --learning-rate 5e-4 --max-patience 250 --num-epochs 2000 --n-neurons 256 --n-blocks-per-transform 6 --num-bins 16