Universe = vanilla
Executable = /data/gravwav/twouters/miniconda3/envs/eos_source_classification/bin/python
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/pe.py --GW-event $(GW_event) --population-type $(population_type) --prior-name $(prior_name) --eos-samples-name $(eos_samples_name) --seed $(seed) --n-pool 64"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/$(GW_event)/$(population_type)/$(prior_name)/$(eos_samples_name)/log.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/$(GW_event)/$(population_type)/$(prior_name)/$(eos_samples_name)/err.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/$(GW_event)/$(population_type)/$(prior_name)/$(eos_samples_name)/out.out
request_memory = 16GB
request_cpus = 64
request_disk = 16GB
+USeOS = "el9"
+JobCategory = "long"
+MaxWallTime = 345600
Queue 1