Universe = vanilla
Executable = /data/gravwav/twouters/miniconda3/envs/eos_source_classification/bin/python
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/pe.py --label GW170817 --prior-name default --seed 123"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/$(label)/$(prior_name)/log.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/$(label)/$(prior_name)/err.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/$(label)/$(prior_name)/out.out
request_memory = 16GB
request_cpus = 16
request_disk = 16GB
+USeOS = "el9"
+JobCategory = "long"
+MaxWallTime = 345600
Queue 1