Universe = vanilla
Executable = /data/gravwav/twouters/miniconda3/envs/eos_source_classification/bin/python
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/cornerplots.py --run-all --gw-event GW190425"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/log.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/err.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/out.out
request_memory = 4GB
request_cpus = 1
request_disk = 2GB
+USeOS = "el9"
+JobCategory = "short"
+MaxWallTime = 3600
Queue 1