Universe = vanilla
Executable = /data/gravwav/twouters/miniconda3/envs/eos_source_classification/bin/python
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/NFprior/train_NF_prior.py --population-type double_gaussian --source-type bns --eos-samples-name radio_chiEFT_NICER --no-use-tilde --no-use-component-masses --N-samples-training 50000 --N-samples-plot 10000 --m-max-BH 5.0 --no-take-log-lambda --no-use-flowjax --scale-input --num-epochs 1500 --learning-rate 0.0005 --batch-size 256 --max-patience 200 --n-transforms 3 --n-neurons 128 --n-blocks-per-transform 3 --num-bins 8 --glasflow-type MaskedPiecewiseRationalQuadraticAutoregressiveFlow --nn-depth 1 --nn-block-dim 8 --flow-layers 1 --validation-split-fraction 0.2 --constrain-flowjax-dist"
getenv = true
Log = ./models/double_gaussian/bns/radio_chiEFT_NICER/log.log
Error = ./models/double_gaussian/bns/radio_chiEFT_NICER/err.err
Output = ./models/double_gaussian/bns/radio_chiEFT_NICER/out.out
request_memory = 16GB
request_cpus = 1
request_disk = 16GB
request_gpus = 1
requirements = regexp("L40S", TARGET.GPUs_DeviceName)
+USeOS = "el9"
+JobCategory = "long"
+MaxWallTime = 345600
Queue 1
