################################################################################
## Calibration arguments
################################################################################

calibration-model=CubicSpline
spline-calibration-nodes=10
spline-calibration-amplitude-uncertainty-dict=None
spline-calibration-phase-uncertainty-dict=None
calibration-prior-boundary=reflective

################################################################################
## Data generation arguments
################################################################################

trigger-time={{{TRIGGER_TIME}}}
data-dict={{{DATA_DICT}}}
channel-dict={{{CHANNEL_DICT}}}

################################################################################
## Detector arguments
################################################################################

detectors={{{DETECTORS}}}
duration=128.0
psd-dict={{{PSD_DICT}}}
psd-fractional-overlap=0.5
post-trigger-duration=2.0
sampling-frequency={{{SAMPLING_FREQUENCY}}}
psd-length=8
psd-maximum-duration=256
psd-method=median
psd-start-time=None
maximum-frequency={{{MAXIMUM_FREQUENCY}}}
minimum-frequency={{{MINIMUM_FREQUENCY}}}
tukey-roll-off=0.4
resampling-method=lal

################################################################################
## Job submission arguments
################################################################################

label={{{LABEL}}}
local=False
local-generation=False
local-plot=True
outdir=outdir
periodic-restart-time=28800
request-memory-generation=8.0
request-memory=500.0
request-cpus={{{NPOOL}}}
request-disk=5.0
scheduler=SLURM
scheduler-args=None
scheduler-module=None
scheduler-env=None
log-directory=None
osg=False
desired-sites=None
transfer-files=False
scheduler-analysis-time=1-00:00:00

################################################################################
## Likelihood arguments
################################################################################

calibration-marginalization=False
distance-marginalization=True
distance-marginalization-lookup-table=None
phase-marginalization=False
time-reference={{{TIME_REFERENCE}}}
likelihood-type=MBGravitationalWaveTransient
calibration-lookup-table=None
number-of-response-curves=1000

################################################################################
## Output arguments
################################################################################

result-format=hdf5
final-result=True
final-result-nsamples=20000

################################################################################
## Prior arguments
################################################################################

default-prior=BNSPriorDict
deltaT=0.2
prior-file=prior.prior
enforce-signal-duration=False

################################################################################
## Sampler arguments
################################################################################

sampler=dynesty
sampling-seed=1
sampler-kwargs={'nlive': 4096, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'npool': {{{NPOOL}}}}
reweighting-configuration=None
reweight-nested-samples=True
 
################################################################################
## Waveform arguments
################################################################################

waveform-generator=bilby.gw.waveform_generator.LALCBCWaveformGenerator
reference-frequency={{{REFERENCE_FREQUENCY}}}
waveform-approximant=IMRPhenomXP_NRTidalv3
frequency-domain-source-model=lal_binary_neutron_star