Universe = vanilla
Executable = /data/gravwav/twouters/miniconda3/envs/eos_source_classification/bin/python

# EOS comparison: fix population=uniform, source=bns, vary eos
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/cornerplots.py --gw-event GW190425 --comparison-mode eos --population-type uniform --source-type bns --convert-lambdas"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/log_eos_uniform_bns_tilde.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/err_eos_uniform_bns_tilde.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/out_eos_uniform_bns_tilde.out
request_memory = 4GB
request_cpus = 1
request_disk = 2GB
+USeOS = "el9"
+JobCategory = "short"
+MaxWallTime = 3600
Queue 1

# EOS comparison: fix population=uniform, source=bns, vary eos (no lambda conversion)
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/cornerplots.py --gw-event GW190425 --comparison-mode eos --population-type uniform --source-type bns --no-convert-lambdas"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/log_eos_uniform_bns.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/err_eos_uniform_bns.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/out_eos_uniform_bns.out
request_memory = 4GB
request_cpus = 1
request_disk = 2GB
+USeOS = "el9"
+JobCategory = "short"
+MaxWallTime = 3600
Queue 1

# EOS comparison: fix population=uniform, source=nsbh, vary eos
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/cornerplots.py --gw-event GW190425 --comparison-mode eos --population-type uniform --source-type nsbh --convert-lambdas"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/log_eos_uniform_nsbh_tilde.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/err_eos_uniform_nsbh_tilde.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/out_eos_uniform_nsbh_tilde.out
request_memory = 4GB
request_cpus = 1
request_disk = 2GB
+USeOS = "el9"
+JobCategory = "short"
+MaxWallTime = 3600
Queue 1

# EOS comparison: fix population=uniform, source=nsbh, vary eos (no lambda conversion)
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/cornerplots.py --gw-event GW190425 --comparison-mode eos --population-type uniform --source-type nsbh --no-convert-lambdas"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/log_eos_uniform_nsbh.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/err_eos_uniform_nsbh.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/cornerplots/out_eos_uniform_nsbh.out
request_memory = 4GB
request_cpus = 1
request_disk = 2GB
+USeOS = "el9"
+JobCategory = "short"
+MaxWallTime = 3600
Queue 1