Universe = vanilla
Executable = /data/gravwav/twouters/miniconda3/envs/eos_source_classification/bin/python
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/NFprior/train_NF_prior.py --population-type uniform --source-type nsbh --eos-samples-name radio"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/NFprior/models/uniform/nsbh/radio/log.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/NFprior/models/uniform/nsbh/radio/err.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/NFprior/models/uniform/nsbh/radio/out.out
request_memory = 16GB
request_cpus = 1
request_disk = 16GB
request_gpus = 1
requirements = regexp("L40S", TARGET.GPUs_DeviceName)
+USeOS = "el9"
+JobCategory = "long"
+MaxWallTime = 345600
Queue 1