Universe = vanilla
Executable = /bin/bash
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/run_cornerplots.sh"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/log.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/err.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/postprocessing/out.out
request_memory = 4GB
request_cpus = 1
request_disk = 2GB
+USeOS = "el9"
+JobCategory = "short"
+MaxWallTime = 3600
Queue 1