################################################################################
## Calibration arguments
################################################################################

calibration-model=CubicSpline
spline-calibration-nodes=10
spline-calibration-amplitude-uncertainty-dict=None
spline-calibration-phase-uncertainty-dict=None
calibration-prior-boundary=reflective

################################################################################
## Data generation arguments
################################################################################

trigger-time=1369419318.7460938
data-dict={'L1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW230529/L-L1_GWOSC_16KHZ_R1-1369417271-4096.gwf'}
channel-dict={'L1': 'L1:GWOSC-16KHZ_R1_STRAIN'}

################################################################################
## Detector arguments
################################################################################

detectors=['L1']
duration=128.0
psd-dict={'L1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW230529/psd_4096.dat'}
psd-fractional-overlap=0.5
post-trigger-duration=2.0
sampling-frequency=4096.0
psd-length=8
psd-maximum-duration=256
psd-method=median
psd-start-time=None
maximum-frequency=1792.0
minimum-frequency=20.0
tukey-roll-off=0.4
resampling-method=lal

################################################################################
## Job submission arguments
################################################################################

label=GW230529
local=False
local-generation=False
local-plot=True
outdir=outdir
periodic-restart-time=28800
request-memory-generation=8.0
request-memory=500.0
request-cpus=96
request-disk=5.0
scheduler=SLURM
scheduler-args=None
scheduler-module=None
scheduler-env=None
log-directory=None
osg=False
desired-sites=None
transfer-files=False
scheduler-analysis-time=1-00:00:00

################################################################################
## Likelihood arguments
################################################################################

calibration-marginalization=False
distance-marginalization=False
distance-marginalization-lookup-table=None
phase-marginalization=False
time-reference=L1
likelihood-type=MBGravitationalWaveTransient
calibration-lookup-table=None
number-of-response-curves=1000

################################################################################
## Output arguments
################################################################################

result-format=hdf5
final-result=True
final-result-nsamples=20000

################################################################################
## Prior arguments
################################################################################

default-prior=BNSPriorDict
deltaT=0.2
prior-file=prior.prior
enforce-signal-duration=False

################################################################################
## Sampler arguments
################################################################################

sampler=dynesty
sampling-seed=1
sampler-kwargs={'nlive': 4096, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'npool': 96}
reweighting-configuration=None
reweight-nested-samples=True
 
################################################################################
## Waveform arguments
################################################################################

waveform-generator=bilby.gw.waveform_generator.LALCBCWaveformGenerator
reference-frequency=20.0
waveform-approximant=IMRPhenomXP_NRTidalv3
frequency-domain-source-model=lal_binary_neutron_star