################################################################################
## Calibration arguments
################################################################################

calibration-model=CubicSpline
spline-calibration-nodes=10
spline-calibration-amplitude-uncertainty-dict=None
spline-calibration-phase-uncertainty-dict=None
calibration-prior-boundary=reflective

################################################################################
## Data generation arguments
################################################################################

trigger-time=1187008882.43
data-dict={'H1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW170817/H-H1_LOSC_CLN_16_V1-1187007040-2048.gwf', 'L1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW170817/L-L1_LOSC_CLN_16_V1-1187007040-2048.gwf', 'V1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW170817/V-V1_LOSC_CLN_16_V1-1187007040-2048.gwf'}
channel-dict={'H1': 'H1:LOSC-STRAIN', 'L1': 'L1:LOSC-STRAIN', 'V1': 'V1:LOSC-STRAIN'}

################################################################################
## Detector arguments
################################################################################

detectors=['H1', 'L1', 'V1']
duration=128.0
psd-dict={'H1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW170817/h1_psd.txt', 'L1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW170817/l1_psd.txt', 'V1': '/home/wouters/projects/eos_source_classification/eos_source_classification/data/GW170817/v1_psd.txt'}
psd-fractional-overlap=0.5
post-trigger-duration=2.0
sampling-frequency=4096.0
psd-length=8
psd-maximum-duration=256
psd-method=median
psd-start-time=None
maximum-frequency=2048.0
minimum-frequency=23.1
tukey-roll-off=0.4
resampling-method=lal

################################################################################
## Job submission arguments
################################################################################

label=GW170817
local=False
local-generation=False
local-plot=True
outdir=outdir
periodic-restart-time=28800
request-memory-generation=8.0
request-memory=500.0
request-cpus=96
request-disk=5.0
scheduler=SLURM
scheduler-args=None
scheduler-module=None
scheduler-env=None
log-directory=None
osg=False
desired-sites=None
transfer-files=False
scheduler-analysis-time=1-00:00:00

################################################################################
## Likelihood arguments
################################################################################

calibration-marginalization=False
distance-marginalization=False
distance-marginalization-lookup-table=None
phase-marginalization=False
time-reference=H1
likelihood-type=MBGravitationalWaveTransient
calibration-lookup-table=None
number-of-response-curves=1000

################################################################################
## Output arguments
################################################################################

result-format=hdf5
final-result=True
final-result-nsamples=20000

################################################################################
## Prior arguments
################################################################################

default-prior=BNSPriorDict
deltaT=0.2
prior-file=prior.prior
enforce-signal-duration=False

################################################################################
## Sampler arguments
################################################################################

sampler=dynesty
sampling-seed=1
sampler-kwargs={'nlive': 4096, 'naccept': 60, 'check_point_plot': True, 'check_point_delta_t': 1800, 'print_method': 'interval-60', 'sample': 'acceptance-walk', 'npool': 96}
reweighting-configuration=None
reweight-nested-samples=True
 
################################################################################
## Waveform arguments
################################################################################

waveform-generator=bilby.gw.waveform_generator.LALCBCWaveformGenerator
reference-frequency=23.1
waveform-approximant=IMRPhenomXP_NRTidalv3
frequency-domain-source-model=lal_binary_neutron_star