Universe = vanilla
Executable = /data/gravwav/twouters/miniconda3/envs/eos_source_classification/bin/python
arguments = "/data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/pe.py --label GW170817 --prior-name $(prior_name) --eos-samples-name radio --GW170817-HV --output-dir /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/HV/"
getenv = true
Log = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/HV/GW170817/$(prior_name)/log.log
Error = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/HV/GW170817/$(prior_name)/err.err
Output = /data/gravwav/twouters/projects/eos_source_classification/eos_source_classification/GW_runs/HV/GW170817/$(prior_name)/out.out
request_memory = 16GB
request_cpus = 64
request_disk = 16GB
+USeOS = "el9"
+JobCategory = "long"
+MaxWallTime = 345600
Queue 1